@extends('layouts.app')

@section('app_css')
    {!! $cdv_document_generation_templates->render_css() !!}
@stop

@section('title_postfix')
Document Generation
@stop

@section('page_title')
Document Generation
@stop

@section('page_title_suffix')
All Templates
@stop

@section('page_title_subtext')
<a class="ms-1" href="{{ route('dashboard') }}">
    <i class="bx bx-chevron-left"></i> Back to Dashboard
</a>
@stop

@section('page_title_buttons')
<a id="btn-new-mdl-documentGenerationTemplate-modal" class="btn btn-sm btn-primary btn-new-mdl-documentGenerationTemplate-modal">
    <i class="bx bx-book-add me-1"></i>New Template
</a>
@stop

@section('content')
    
    <div class="card border-top border-0 border-4 border-primary">
        <div class="card-body">
            {{ $cdv_document_generation_templates->render() }}
        </div>
    </div>

    @include('hasob-foundation-core::document_generation_templates.modal')
@stop

@section('side-panel')
<div class="card radius-5 border-top border-0 border-4 border-primary">
    <div class="card-body">
        <div><h5 class="card-title">Doccument Template</h5></div>
        <p class="small">
            Documents can be generated by different aspects of this application. These templates provide the basis for documents being generated.
        </p>
    </div>
</div>
@stop

@push('page_scripts')
    {!! $cdv_document_generation_templates->render_js() !!}
@endpush